2020-05-21 19:55:45,277 ERROR: 
            Exception on /api/users/tasks/523 [PUT] [in /home/lean/Arhat/venv/lib/python3.7/site-packages/flask/app.py:
            1892]
            
Traceback (most recent call last):
  File "/home/lean/Arhat/venv/lib/python3.7/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/lean/Arhat/venv/lib/python3.7/site-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/lean/Arhat/venv/lib/python3.7/site-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/lean/Arhat/venv/lib/python3.7/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/home/lean/Arhat/venv/lib/python3.7/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/lean/Arhat/venv/lib/python3.7/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/lean/Arhat/venv/lib/python3.7/site-packages/flask_httpauth.py", line 162, in decorated
    return f(*args, **kwargs)
  File "/home/lean/Arhat/app/api/users.py", line 89, in update_task
    task.from_dict(data)
  File "/home/lean/Arhat/app/models.py", line 505, in from_dict
    data['frequency'] = int(data['frequency'])
ValueError: invalid literal for int() with base 10: 'None'
2020-05-21 20:00:26,312 ERROR: 
            Exception on /api/users/tasks/524 [PUT] [in /home/lean/Arhat/venv/lib/python3.7/site-packages/flask/app.py:
            1892]
            
Traceback (most recent call last):
  File "/home/lean/Arhat/venv/lib/python3.7/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/lean/Arhat/venv/lib/python3.7/site-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/lean/Arhat/venv/lib/python3.7/site-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/lean/Arhat/venv/lib/python3.7/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/home/lean/Arhat/venv/lib/python3.7/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/lean/Arhat/venv/lib/python3.7/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/lean/Arhat/venv/lib/python3.7/site-packages/flask_httpauth.py", line 162, in decorated
    return f(*args, **kwargs)
  File "/home/lean/Arhat/app/api/users.py", line 89, in update_task
    task.from_dict(data)
  File "/home/lean/Arhat/app/models.py", line 505, in from_dict
    data['frequency'] = int(data['frequency'])
ValueError: invalid literal for int() with base 10: 'None'
