2020-05-09 18:00:35,645 ERROR: 
            Exception on /edit_task/ [POST] [in /home/lean/Arhat/venv/lib/python3.7/site-packages/flask/app.py:
            1892]
            
Traceback (most recent call last):
  File "/home/lean/Arhat/venv/lib/python3.7/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/lean/Arhat/venv/lib/python3.7/site-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/lean/Arhat/venv/lib/python3.7/site-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/lean/Arhat/venv/lib/python3.7/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/home/lean/Arhat/venv/lib/python3.7/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/lean/Arhat/venv/lib/python3.7/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/lean/Arhat/venv/lib/python3.7/site-packages/flask_login/utils.py", line 272, in decorated_view
    return func(*args, **kwargs)
  File "/home/lean/Arhat/app/main/routes.py", line 267, in edit_task
    edit_task.edit_all_freq_parent_and_child_tasks()
  File "/home/lean/Arhat/app/main/routes.py", line 229, in edit_all_freq_parent_and_child_tasks
    elif ((self.parent_task.date - task.date).days % int(self.form.frequency.data)) != 0:
TypeError: int() argument must be a string, a bytes-like object or a number, not 'NoneType'
2020-05-09 18:02:46,938 INFO: 
            Template startup [in /home/lean/Arhat/app/__init__.py:
            91]
            
2020-05-09 19:35:02,605 INFO: 
            Template startup [in /home/lean/Arhat/app/__init__.py:
            91]
            
2020-05-09 19:35:08,769 ERROR: 
            Exception on /edit_task/ [POST] [in /home/lean/Arhat/venv/lib/python3.7/site-packages/flask/app.py:
            1892]
            
Traceback (most recent call last):
  File "/home/lean/Arhat/venv/lib/python3.7/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/lean/Arhat/venv/lib/python3.7/site-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/lean/Arhat/venv/lib/python3.7/site-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/lean/Arhat/venv/lib/python3.7/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/home/lean/Arhat/venv/lib/python3.7/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/lean/Arhat/venv/lib/python3.7/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/lean/Arhat/venv/lib/python3.7/site-packages/flask_login/utils.py", line 272, in decorated_view
    return func(*args, **kwargs)
  File "/home/lean/Arhat/app/main/routes.py", line 270, in edit_task
    edit_task.edit_all_freq_parent_and_child_tasks()
  File "/home/lean/Arhat/app/main/routes.py", line 215, in edit_all_freq_parent_and_child_tasks
    self.parent_task = current_user.posts.filter_by(id=self.task_to_be_edited.exclude).last()
AttributeError: 'BaseQuery' object has no attribute 'last'
2020-05-09 19:36:05,919 INFO: 
            Template startup [in /home/lean/Arhat/app/__init__.py:
            91]
            
2020-05-09 19:38:55,634 INFO: 
            Template startup [in /home/lean/Arhat/app/__init__.py:
            91]
            
2020-05-09 19:39:22,390 INFO: 
            Template startup [in /home/lean/Arhat/app/__init__.py:
            91]
            
2020-05-09 19:40:51,995 INFO: 
            Template startup [in /home/lean/Arhat/app/__init__.py:
            91]
            
2020-05-09 19:41:29,463 INFO: 
            Template startup [in /home/lean/Arhat/app/__init__.py:
            91]
            
2020-05-09 19:42:13,448 INFO: 
            Template startup [in /home/lean/Arhat/app/__init__.py:
            91]
            
2020-05-09 19:44:02,375 INFO: 
            Template startup [in /home/lean/Arhat/app/__init__.py:
            91]
            
2020-05-09 19:45:34,462 INFO: 
            Template startup [in /home/lean/Arhat/app/__init__.py:
            91]
            
2020-05-09 19:47:03,649 INFO: 
            Template startup [in /home/lean/Arhat/app/__init__.py:
            91]
            
2020-05-09 19:47:54,560 INFO: 
            Template startup [in /home/lean/Arhat/app/__init__.py:
            91]
            
2020-05-09 20:51:49,618 INFO: 
            Template startup [in /home/lean/Arhat/app/__init__.py:
            91]
            
2020-05-09 23:11:46,060 ERROR: 
            Exception on /new_task/ [POST] [in /home/lean/Arhat/venv/lib/python3.7/site-packages/flask/app.py:
            1892]
            
Traceback (most recent call last):
  File "/home/lean/Arhat/venv/lib/python3.7/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/lean/Arhat/venv/lib/python3.7/site-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/lean/Arhat/venv/lib/python3.7/site-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/lean/Arhat/venv/lib/python3.7/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/home/lean/Arhat/venv/lib/python3.7/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/lean/Arhat/venv/lib/python3.7/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/lean/Arhat/venv/lib/python3.7/site-packages/flask_login/utils.py", line 272, in decorated_view
    return func(*args, **kwargs)
  File "/home/lean/Arhat/app/main/routes.py", line 141, in new_task
    frequency=new_task.form.frequency.data,
  File "/home/lean/Arhat/app/main/routes.py", line 114, in add_single_task
    to_date=to_date
TypeError: __init__() got an unexpected keyword argument 'date'
2020-05-09 23:12:16,894 INFO: 
            Template startup [in /home/lean/Arhat/app/__init__.py:
            91]
            
2020-05-10 14:26:18,493 INFO: 
            Template startup [in /home/lean/Arhat/app/__init__.py:
            91]
            
2020-05-10 17:12:48,463 INFO: 
            Template startup [in /home/lean/Arhat/app/__init__.py:
            91]
            
