2020-05-28 23:41:46,303 ERROR: 
            Exception on /api/users/send/4/2/test [POST] [in /home/lean/Arhat/venv/lib/python3.7/site-packages/flask/app.py:
            1892]
            
Traceback (most recent call last):
  File "/home/lean/Arhat/venv/lib/python3.7/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/lean/Arhat/venv/lib/python3.7/site-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/lean/Arhat/venv/lib/python3.7/site-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/lean/Arhat/venv/lib/python3.7/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/home/lean/Arhat/venv/lib/python3.7/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/lean/Arhat/venv/lib/python3.7/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/lean/Arhat/venv/lib/python3.7/site-packages/flask_httpauth.py", line 162, in decorated
    return f(*args, **kwargs)
  File "/home/lean/Arhat/app/api/users.py", line 205, in send_message
    # body = json.loads(body)
  File "/usr/lib/python3.7/json/__init__.py", line 348, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python3.7/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python3.7/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
2020-05-28 23:42:17,334 INFO: 
            Template startup [in /home/lean/Arhat/app/__init__.py:
            97]
            
2020-05-28 23:48:33,736 INFO: 
            Template startup [in /home/lean/Arhat/app/__init__.py:
            97]
            
2020-05-28 23:54:22,284 INFO: 
            Template startup [in /home/lean/Arhat/app/__init__.py:
            97]
            
2020-05-29 00:06:16,685 INFO: 
            Template startup [in /home/lean/Arhat/app/__init__.py:
            97]
            
2020-05-29 00:09:13,924 INFO: 
            Template startup [in /home/lean/Arhat/app/__init__.py:
            97]
            
2020-05-29 00:22:20,499 INFO: 
            Template startup [in /home/lean/Arhat/app/__init__.py:
            97]
            
2020-05-29 00:25:20,043 INFO: 
            Template startup [in /home/lean/Arhat/app/__init__.py:
            97]
            
2020-05-30 12:32:20,885 INFO: 
            Template startup [in /home/lean/Arhat/app/__init__.py:
            97]
            
2020-05-30 13:05:39,161 INFO: 
            Template startup [in /home/lean/Arhat/app/__init__.py:
            97]
            
2020-05-30 13:09:12,758 INFO: 
            Template startup [in /home/lean/Arhat/app/__init__.py:
            97]
            
2020-05-30 13:10:06,152 INFO: 
            Template startup [in /home/lean/Arhat/app/__init__.py:
            97]
            
2020-05-30 13:11:03,775 INFO: 
            Template startup [in /home/lean/Arhat/app/__init__.py:
            97]
            
2020-05-30 13:11:44,409 ERROR: 
            Exception on /api/users/tasks/2/30-05-2020 [POST] [in /home/lean/Arhat/venv/lib/python3.7/site-packages/flask/app.py:
            1892]
            
Traceback (most recent call last):
  File "/home/lean/Arhat/venv/lib/python3.7/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/lean/Arhat/venv/lib/python3.7/site-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/lean/Arhat/venv/lib/python3.7/site-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/lean/Arhat/venv/lib/python3.7/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/home/lean/Arhat/venv/lib/python3.7/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/lean/Arhat/venv/lib/python3.7/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/lean/Arhat/app/api/users.py", line 123, in create_task
    task.from_dict(data)
  File "/home/lean/Arhat/app/models.py", line 526, in from_dict
    print(f'{field} is {data[field]}')
KeyError: 'done'
2020-05-30 13:13:56,296 INFO: 
            Template startup [in /home/lean/Arhat/app/__init__.py:
            97]
            
2020-05-30 13:15:24,198 INFO: 
            Template startup [in /home/lean/Arhat/app/__init__.py:
            97]
            
2020-05-30 13:16:32,935 INFO: 
            Template startup [in /home/lean/Arhat/app/__init__.py:
            97]
            
