2020-04-29 21:47:42,565 INFO: 
            Template startup [in /home/lean/Arhat/app/__init__.py:
            91]
            
2020-04-29 21:52:29,282 INFO: 
            Template startup [in /home/lean/Arhat/app/__init__.py:
            91]
            
2020-04-29 22:13:02,264 INFO: 
            Template startup [in /home/lean/Arhat/app/__init__.py:
            91]
            
2020-04-30 14:00:55,254 INFO: 
            Template startup [in /home/lean/Arhat/app/__init__.py:
            91]
            
2020-04-30 14:34:56,131 INFO: 
            Template startup [in /home/lean/Arhat/app/__init__.py:
            91]
            
2020-04-30 14:44:09,023 INFO: 
            Template startup [in /home/lean/Arhat/app/__init__.py:
            91]
            
2020-04-30 15:09:13,769 INFO: 
            Template startup [in /home/lean/Arhat/app/__init__.py:
            91]
            
2020-04-30 15:09:16,305 ERROR: 
            Exception on /index/01-05-2020 [GET] [in /home/lean/Arhat/venv/lib/python3.7/site-packages/flask/app.py:
            1892]
            
Traceback (most recent call last):
  File "/home/lean/Arhat/venv/lib/python3.7/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/lean/Arhat/venv/lib/python3.7/site-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/lean/Arhat/venv/lib/python3.7/site-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/lean/Arhat/venv/lib/python3.7/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/home/lean/Arhat/venv/lib/python3.7/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/lean/Arhat/venv/lib/python3.7/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/lean/Arhat/venv/lib/python3.7/site-packages/flask_login/utils.py", line 272, in decorated_view
    return func(*args, **kwargs)
  File "/home/lean/Arhat/app/main/routes.py", line 77, in index
    tasks=tasks,
NameError: name 'tasks' is not defined
2020-04-30 15:09:32,314 INFO: 
            Template startup [in /home/lean/Arhat/app/__init__.py:
            91]
            
2020-04-30 15:11:57,383 INFO: 
            Template startup [in /home/lean/Arhat/app/__init__.py:
            91]
            
2020-04-30 15:11:58,981 ERROR: 
            Exception on /index/01-05-2020 [GET] [in /home/lean/Arhat/venv/lib/python3.7/site-packages/flask/app.py:
            1892]
            
Traceback (most recent call last):
  File "/home/lean/Arhat/venv/lib/python3.7/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/lean/Arhat/venv/lib/python3.7/site-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/lean/Arhat/venv/lib/python3.7/site-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/lean/Arhat/venv/lib/python3.7/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/home/lean/Arhat/venv/lib/python3.7/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/lean/Arhat/venv/lib/python3.7/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/lean/Arhat/venv/lib/python3.7/site-packages/flask_login/utils.py", line 272, in decorated_view
    return func(*args, **kwargs)
  File "/home/lean/Arhat/app/main/routes.py", line 78, in index
    task_hours=task_hours,
NameError: name 'task_hours' is not defined
2020-04-30 15:12:31,293 INFO: 
            Template startup [in /home/lean/Arhat/app/__init__.py:
            91]
            
