2020-05-08 14:56:45,288 ERROR: 
            Exception on /index/ph [GET] [in /home/lean/Arhat/venv/lib/python3.7/site-packages/flask/app.py:
            1892]
            
Traceback (most recent call last):
  File "/home/lean/Arhat/venv/lib/python3.7/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/lean/Arhat/venv/lib/python3.7/site-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/lean/Arhat/venv/lib/python3.7/site-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/lean/Arhat/venv/lib/python3.7/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/home/lean/Arhat/venv/lib/python3.7/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/lean/Arhat/venv/lib/python3.7/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/lean/Arhat/venv/lib/python3.7/site-packages/flask_login/utils.py", line 272, in decorated_view
    return func(*args, **kwargs)
  File "/home/lean/Arhat/app/main/routes.py", line 36, in index
    test.form.frequency.data = 2
AttributeError: 'property' object has no attribute 'frequency'
2020-05-08 14:57:24,169 INFO: 
            Template startup [in /home/lean/Arhat/app/__init__.py:
            91]
            
2020-05-08 14:57:26,108 ERROR: 
            Exception on /index/ph [GET] [in /home/lean/Arhat/venv/lib/python3.7/site-packages/flask/app.py:
            1892]
            
Traceback (most recent call last):
  File "/home/lean/Arhat/venv/lib/python3.7/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/lean/Arhat/venv/lib/python3.7/site-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/lean/Arhat/venv/lib/python3.7/site-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/lean/Arhat/venv/lib/python3.7/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/home/lean/Arhat/venv/lib/python3.7/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/lean/Arhat/venv/lib/python3.7/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/lean/Arhat/venv/lib/python3.7/site-packages/flask_login/utils.py", line 272, in decorated_view
    return func(*args, **kwargs)
  File "/home/lean/Arhat/app/main/routes.py", line 36, in index
    test.form.task.data = 2
AttributeError: 'property' object has no attribute 'task'
2020-05-08 14:59:39,415 INFO: 
            Template startup [in /home/lean/Arhat/app/__init__.py:
            91]
            
2020-05-08 14:59:41,339 ERROR: 
            Exception on /index/ph [GET] [in /home/lean/Arhat/venv/lib/python3.7/site-packages/flask/app.py:
            1892]
            
Traceback (most recent call last):
  File "/home/lean/Arhat/venv/lib/python3.7/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/lean/Arhat/venv/lib/python3.7/site-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/lean/Arhat/venv/lib/python3.7/site-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/lean/Arhat/venv/lib/python3.7/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/home/lean/Arhat/venv/lib/python3.7/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/lean/Arhat/venv/lib/python3.7/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/lean/Arhat/venv/lib/python3.7/site-packages/flask_login/utils.py", line 272, in decorated_view
    return func(*args, **kwargs)
  File "/home/lean/Arhat/app/main/routes.py", line 36, in index
    test.form().task.data = 2
TypeError: 'property' object is not callable
2020-05-08 15:00:18,497 INFO: 
            Template startup [in /home/lean/Arhat/app/__init__.py:
            91]
            
2020-05-08 15:14:54,895 INFO: 
            Template startup [in /home/lean/Arhat/app/__init__.py:
            91]
            
2020-05-08 15:18:22,054 INFO: 
            Template startup [in /home/lean/Arhat/app/__init__.py:
            91]
            
2020-05-08 15:34:45,762 INFO: 
            Template startup [in /home/lean/Arhat/app/__init__.py:
            91]
            
2020-05-08 16:04:22,583 INFO: 
            Template startup [in /home/lean/Arhat/app/__init__.py:
            91]
            
2020-05-08 16:04:28,597 ERROR: 
            Exception on /new_task/ [POST] [in /home/lean/Arhat/venv/lib/python3.7/site-packages/flask/app.py:
            1892]
            
Traceback (most recent call last):
  File "/home/lean/Arhat/venv/lib/python3.7/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/lean/Arhat/venv/lib/python3.7/site-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/lean/Arhat/venv/lib/python3.7/site-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/lean/Arhat/venv/lib/python3.7/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/home/lean/Arhat/venv/lib/python3.7/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/lean/Arhat/venv/lib/python3.7/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/lean/Arhat/venv/lib/python3.7/site-packages/flask_login/utils.py", line 272, in decorated_view
    return func(*args, **kwargs)
  File "/home/lean/Arhat/app/main/routes.py", line 95, in new_task
    new_task.calc_mins_height_and_end(form)
  File "/home/lean/Arhat/app/main/routes.py", line 80, in calc_mins_height_and_end
    self.height = ((form.end_time.data.hour * 60) + form.end_time.data.minute) - minutes
NameError: name 'minutes' is not defined
2020-05-08 16:04:55,930 INFO: 
            Template startup [in /home/lean/Arhat/app/__init__.py:
            91]
            
2020-05-08 16:44:44,525 INFO: 
            Template startup [in /home/lean/Arhat/app/__init__.py:
            91]
            
2020-05-08 17:19:16,266 INFO: 
            Template startup [in /home/lean/Arhat/app/__init__.py:
            91]
            
2020-05-08 17:23:08,142 INFO: 
            Template startup [in /home/lean/Arhat/app/__init__.py:
            91]
            
2020-05-08 22:47:35,107 INFO: 
            Template startup [in /home/lean/Arhat/app/__init__.py:
            91]
            
